import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

// Hardcoded entity schemas - workaround para SDK limitação
const ENTITY_SCHEMAS = {
  'Clientes': {"name":"Clientes","type":"object","properties":{"empresa_id":{"type":"string","description":"UUID da empresa (FK → empresas.id) — multi-tenant"},"codigo":{"type":"string","description":"Código interno do cliente"},"nome_cliente":{"type":"string","description":"Razão social ou nome completo"},"nome_fantasia":{"type":"string","description":"Nome fantasia"},"documento":{"type":"string","description":"CPF ou CNPJ"},"tipo_pessoa":{"type":"string","enum":["PF","PJ"],"default":"PJ","description":"Tipo de pessoa"},"inscricao_estadual":{"type":"string","description":"Inscrição estadual"},"situacao_ie":{"type":"string","enum":["Contribuinte","Contribuinte Isento","Não Contribuinte"],"default":"Não Contribuinte"},"email":{"type":"string","description":"E-mail principal"},"telefone":{"type":"string"},"celular":{"type":"string"},"site":{"type":"string"},"endereco":{"type":"string"},"numero":{"type":"string"},"complemento":{"type":"string"},"bairro":{"type":"string"},"cidade":{"type":"string"},"estado":{"type":"string"},"cep":{"type":"string"},"limite_credito":{"type":"number","default":0,"description":"Limite de crédito em reais"},"condicao_pagamento":{"type":"string"},"observacoes":{"type":"string"},"status":{"type":"string","enum":["Ativo","Inativo"],"default":"Ativo"}},"required":["empresa_id","nome_cliente","documento"]},
  'ClienteContatos': {"name":"ClienteContatos","type":"object","properties":{"cliente_id":{"type":"string","description":"UUID do cliente (FK -> clientes.id)"},"empresa_id":{"type":"string","description":"UUID da empresa (FK -> empresas.id)"},"nome":{"type":"string","description":"Nome do contato"},"email":{"type":"string","description":"Email do contato"},"telefone":{"type":"string","description":"Telefone do contato"},"departamento":{"type":"string","description":"Departamento do contato"},"cargo":{"type":"string","description":"Cargo do contato"}},"required":["cliente_id","empresa_id","nome"]},
  'ClienteEnderecos': {"name":"ClienteEnderecos","type":"object","properties":{"cliente_id":{"type":"string","description":"UUID do cliente (FK -> clientes.id)"},"empresa_id":{"type":"string","description":"UUID da empresa (FK -> empresas.id)"},"cep":{"type":"string","description":"CEP do endereço"},"rua":{"type":"string","description":"Nome da rua"},"numero":{"type":"string","description":"Número do imóvel"},"complemento":{"type":"string","description":"Complemento do endereço"},"bairro":{"type":"string","description":"Bairro"},"cidade":{"type":"string","description":"Cidade"},"estado":{"type":"string","description":"Estado (UF)"},"tipo_endereco":{"type":"string","enum":["Cobrança","Entrega","Principal"],"default":"Entrega","description":"Tipo de endereço"}},"required":["cliente_id","empresa_id","cep","rua","numero","cidade","estado"]},
  'Fornecedores': {"name":"Fornecedores","type":"object","properties":{"empresa_id":{"type":"string","description":"UUID da empresa (FK → empresas.id)"},"codigo":{"type":"string","description":"Código interno"},"nome_fornecedor":{"type":"string","description":"Razão social"},"nome_fantasia":{"type":"string"},"documento":{"type":"string","description":"CPF ou CNPJ"},"tipo_pessoa":{"type":"string","enum":["PF","PJ"],"default":"PJ"},"inscricao_estadual":{"type":"string"},"email":{"type":"string"},"telefone":{"type":"string"},"celular":{"type":"string"},"endereco":{"type":"string"},"numero":{"type":"string"},"bairro":{"type":"string"},"cidade":{"type":"string"},"estado":{"type":"string"},"cep":{"type":"string"},"condicao_pagamento":{"type":"string"},"observacoes":{"type":"string"},"status":{"type":"string","enum":["ativo","inativo","bloqueado"],"default":"ativo"}},"required":["empresa_id","nome_fornecedor","documento"]},
  'Produtos': {"name":"Produtos","type":"object","properties":{"empresa_id":{"type":"string","description":"UUID da empresa (FK → empresas.id)"},"codigo":{"type":"string","description":"Código SKU do produto"},"descricao":{"type":"string","description":"Descrição principal"},"descricao_complementar":{"type":"string"},"categoria":{"type":"string"},"tipo_produto":{"type":"string","enum":["Matéria Prima","Produto Acabado","Insumo","Embalagem"],"description":"Classificação do produto"},"unidade_medida":{"type":"string","default":"UN","description":"UN, KG, MT, LT, etc."},"preco_custo":{"type":"number","default":0},"preco_venda":{"type":"number","default":0},"peso_liquido":{"type":"number"},"peso_bruto":{"type":"number"},"status":{"type":"string","enum":["Ativo","Inativo"],"default":"Ativo"}},"required":["empresa_id","descricao","tipo_produto"]},
  'Pedidos': {"name":"Pedidos","type":"object","properties":{"empresa_id":{"type":"string","description":"UUID da empresa (FK → empresas.id)"},"numero_pedido":{"type":"string","description":"Número único do pedido por empresa"},"cliente_id":{"type":"string","description":"UUID do cliente (FK → clientes.id) — substitui cliente_nome"},"vendedor_id":{"type":"string","description":"UUID do vendedor (FK → erp_usuarios.id)"},"transportadora_id":{"type":"string","description":"UUID da transportadora (FK → transportadoras.id)"},"modalidade_frete_id":{"type":"string","description":"UUID da modalidade de frete (FK → modalidade_frete.id)"},"data_pedido":{"type":"string","format":"date","description":"Data do pedido"},"data_entrega_prevista":{"type":"string","format":"date"},"data_entrega_realizada":{"type":"string","format":"date"},"status":{"type":"string","enum":["Rascunho","Confirmado","Em Produção","Pronto","Entregue","Cancelado"],"default":"Rascunho"},"valor_subtotal":{"type":"number","default":0},"valor_desconto":{"type":"number","default":0},"valor_frete":{"type":"number","default":0},"valor_total":{"type":"number","default":0},"observacoes":{"type":"string"}},"required":["empresa_id","numero_pedido","cliente_id"]},
  'PedidosItens': {"name":"PedidosItens","type":"object","properties":{"empresa_id":{"type":"string","description":"UUID da empresa (FK → empresas.id)"},"pedido_id":{"type":"string","description":"UUID do pedido (FK → pedidos.id) — chave de relacionamento"},"produto_id":{"type":"string","description":"UUID do produto (FK → produtos.id) — substitui campo texto produto"},"sequencia":{"type":"number","description":"Ordem do item no pedido"},"quantidade":{"type":"number","description":"Quantidade do produto"},"preco_unitario":{"type":"number","description":"Preço unitário no momento do pedido"},"valor_desconto":{"type":"number","default":0},"observacoes":{"type":"string"}},"required":["empresa_id","pedido_id","produto_id","quantidade","preco_unitario"]},
};

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    return Response.json({ 
      schemas: ENTITY_SCHEMAS,
      timestamp: new Date().toISOString(),
      loadedCount: Object.keys(ENTITY_SCHEMAS).length,
      source: 'hardcoded_schemas'
    });
  } catch (error) {
    console.error('readEntitySchemas error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});